name: Validate Environmental Variables

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'

permissions:
  contents: write
  actions: read

jobs:
  process-jira-event:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install @anthropic-ai/sdk
          npm install

      - name: Validate Environment Variables
        run: |
          echo "Checking required environment variables..."
          if [ -z "${{ secrets.JIRA_EMAIL }}" ]; then
            echo "ERROR: JIRA_EMAIL not set"
            exit 1
          fi
          if [ -z "${{ secrets.JIRA_API_TOKEN }}" ]; then
            echo "ERROR: JIRA_API_TOKEN not set"
            exit 1
          fi
          if [ -z "${{ secrets.JIRA_URL }}" ]; then
            echo "ERROR: JIRA_URL not set"
            exit 1
          fi
          if [ -z "${{ secrets.CLAUDE_API_KEY }}" ]; then
            echo "ERROR: CLAUDE_API_KEY not set"
            exit 1
          fi
          echo "All environment variables present"

      - name: Validate Jira Credentials
        run: |
          echo "Testing Jira API connection..."
          
          # Test authentication with /myself endpoint
          MYSELF_RESPONSE=$(curl -s -w "HTTP_CODE:%{http_code}" \
            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -H "Accept: application/json" \
            "${{ secrets.JIRA_URL }}/rest/api/2/myself")
          
          echo "Jira Auth Response: $MYSELF_RESPONSE"
          
          MYSELF_CODE=$(echo "$MYSELF_RESPONSE" | grep -o 'HTTP_CODE:[0-9]*' | cut -d: -f2)
          if [ "$MYSELF_CODE" != "200" ]; then
            echo "ERROR: Jira authentication failed with code: $MYSELF_CODE"
            exit 1
          fi
          
          echo "Jira authentication successful"
          
          # Test project access
          echo "Testing PCP1 project access..."
          PROJECT_RESPONSE=$(curl -s -w "HTTP_CODE:%{http_code}" \
            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -H "Accept: application/json" \
            "${{ secrets.JIRA_URL }}/rest/api/2/project/PCP1")
          
          PROJECT_CODE=$(echo "$PROJECT_RESPONSE" | grep -o 'HTTP_CODE:[0-9]*' | cut -d: -f2)
          if [ "$PROJECT_CODE" != "200" ]; then
            echo "ERROR: Cannot access PCP1 project. Code: $PROJECT_CODE"
            echo "Response: $PROJECT_RESPONSE"
            exit 1
          fi
          
          echo "PCP1 project access confirmed"

      - name: Validate Claude API
        run: |
          echo "Testing Claude API connection..."
          TEST_RESPONSE=$(curl -s -w "HTTP_CODE:%{http_code}" \
            -H "x-api-key: ${{ secrets.CLAUDE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "anthropic-version: 2023-06-01" \
            "https://api.anthropic.com/v1/messages" \
            -d '{
              "model": "claude-3-5-sonnet-20241022",
              "max_tokens": 10,
              "messages": [{"role": "user", "content": "test"}]
            }')
          
          CLAUDE_CODE=$(echo "$TEST_RESPONSE" | grep -o 'HTTP_CODE:[0-9]*' | cut -d: -f2)
          if [ "$CLAUDE_CODE" != "200" ]; then
            echo "ERROR: Claude API test failed with code: $CLAUDE_CODE"
            echo "Response: $TEST_RESPONSE"
            exit 1
          fi
          
          echo "Claude API connection successful"
      - name: Complete
        run: |
          echo "All checks passed successfully."